package com.example.ui.dashboard

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream

object PdfGenerator {
    fun createReport(
        context: Context,
        wins: Int,
        losses: Int,
        winRate: Float,
        profitFactor: Double,
        avgDrawdown: Double,
        totalTrades: Int
    ): File {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 format
        val page = document.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()

        // Background
        paint.color = Color.WHITE
        canvas.drawRect(0f, 0f, 595f, 842f, paint)

        // Header
        paint.color = Color.BLACK
        paint.textSize = 28f
        paint.isFakeBoldText = true
        canvas.drawText("Historical Signal Performance Report", 50f, 80f, paint)

        paint.textSize = 14f
        paint.isFakeBoldText = false
        paint.color = Color.DKGRAY
        canvas.drawText("Generated by Trading Analyze", 50f, 110f, paint)

        // Divider
        paint.color = Color.LTGRAY
        paint.strokeWidth = 2f
        canvas.drawLine(50f, 130f, 545f, 130f, paint)

        // Content
        paint.color = Color.BLACK
        paint.textSize = 18f
        var y = 170f
        val lineSpacing = 35f

        paint.isFakeBoldText = true
        canvas.drawText("Summary Statistics", 50f, y, paint)
        y += lineSpacing
        paint.isFakeBoldText = false
        
        canvas.drawText("Total Signals/Trades:     $totalTrades", 50f, y, paint); y += lineSpacing
        canvas.drawText("Winning Trades:           $wins", 50f, y, paint); y += lineSpacing
        canvas.drawText("Losing Trades:            $losses", 50f, y, paint); y += lineSpacing
        canvas.drawText("Win/Loss Ratio:           ${String.format("%.2f", winRate)}%", 50f, y, paint); y += lineSpacing
        canvas.drawText("Profit Factor:            ${String.format("%.2f", profitFactor)}", 50f, y, paint); y += lineSpacing
        canvas.drawText("Average Drawdown:         ${String.format("%.2f", avgDrawdown)}%", 50f, y, paint); y += lineSpacing
        
        y += 20f
        paint.color = Color.LTGRAY
        canvas.drawLine(50f, y, 545f, y, paint)
        y += 30f
        
        paint.color = Color.BLACK
        paint.textSize = 14f
        canvas.drawText("Strategy effectiveness is continually evaluated by the adaptive brain.", 50f, y, paint)

        document.finishPage(page)

        val directory = File(context.getExternalFilesDir(null), "Reports")
        if (!directory.exists()) {
            directory.mkdirs()
        }
        val file = File(directory, "Trading_Performance_Report_${System.currentTimeMillis()}.pdf")
        document.writeTo(FileOutputStream(file))
        document.close()

        return file
    }
}
